from alpine

RUN mkdir /dir-with-whiteout && touch /dir-with-whiteout/file
RUN rm /dir-with-whiteout/file

RUN mkdir /dir-removed-and-recreated-as-file-on-same-layer
RUN rm -r /dir-removed-and-recreated-as-file-on-same-layer && touch /dir-removed-and-recreated-as-file-on-same-layer

RUN touch /file-removed-and-recreated-as-dir-on-same-layer
RUN rm /file-removed-and-recreated-as-dir-on-same-layer && mkdir /file-removed-and-recreated-as-dir-on-same-layer

RUN mkdir /dir-with-artificial-whiteout && touch /dir-with-artificial-whiteout/.wh.file && touch /dir-with-artificial-whiteout/file

RUN touch /file-in-root-folder
RUN rm /file-in-root-folder
