FROM spack/ubuntu-bionic:0.16.2

# Install builtin dependencies for Sarus
RUN spack install wget
RUN spack install cmake
RUN spack install openssl
RUN spack install squashfs
RUN spack install python@3:

ENTRYPOINT []
CMD []

