#
# Sarus
#
# Copyright (c) 2018-2023, ETH Zurich. All rights reserved.
#
# Please, refer to the LICENSE file in the root directory.
# SPDX-License-Identifier: BSD-3-Clause
#
# -------------------------------------------
#
# Docker Image used to build Sarus from its source,
# but with cached dependencies already in this image.
#
FROM rockylinux:8

COPY ./installation/ /tmp/
RUN /tmp/install_sudo.sh rocky:8
RUN /tmp/install_packages_rocky:8.sh
RUN bash -i -c "/tmp/install_dep_umoci.bash"
RUN python3 -m venv /sarus-venv \
    && . /sarus-venv/bin/activate \
    && pip3 install -r /tmp/requirements_tests.txt

RUN useradd -m docker \
    && echo 'docker:docker' | chpasswd \
    && chown docker:docker /home/docker \
    && echo 'docker ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers \
    && echo 'export PATH=${PATH}:/usr/local/bin' >> /home/docker/.bashrc \
    && echo 'export PATH=${PATH}:/usr/local/bin' >> /root/.bashrc
USER docker
WORKDIR /home/docker

CMD ["/bin/bash"]
