FROM opensuse/leap:15.2

# Install packages required by Spack
# glibc-devel-static is required for building the SSH hook's custom OpenSSH software
RUN zypper install -y                                             \
        curl findutils gcc gcc-c++ gcc-fortran glibc-devel-static \
        git gpg2 hostname iproute lua-lmod make patch openssh     \
        python python-pip tcl unzip which tar gzip xz lbzip2      \
    && pip install boto3                                          \
    && zypper clean --all

# Install and configure Spack
ENV SPACK_ROOT=/opt/spack
ENV PATH=${PATH}:${SPACK_ROOT}/bin
RUN git clone https://github.com/spack/spack.git ${SPACK_ROOT} \
    && git --git-dir=${SPACK_ROOT}/.git --work-tree=${SPACK_ROOT} checkout v0.16.2 \
    && . ${SPACK_ROOT}/share/spack/setup-env.sh

# Install builtin dependencies for Sarus
ENV FORCE_UNSAFE_CONFIGURE=1
RUN spack install wget
RUN spack install cmake
RUN spack install openssl
RUN spack install squashfs
RUN spack install cpprestsdk@2.10.0: ^boost@1.65.0: cxxstd=11
RUN spack install libarchive@3.4.1:
RUN spack install python@3:

