FROM spack/ubuntu-bionic

# Install builtin dependencies for Sarus
RUN spack install wget
RUN spack install cmake
RUN spack install openssl
RUN spack install squashfs
RUN spack install boost@1.65.0 cxxstd=11
RUN spack install --no-checksum libarchive@3.4.1
RUN spack install python@3:

ENTRYPOINT []
CMD []

